#Auto-incremented release version
#Wed Aug 19 11:11:34 IST 2026
releaseNotes=Bug fixes and stability improvements.
baseApkUrl=https\://feedpilot-api-ount.onrender.com/apk
forceUpdate=false
versionName=2.0.99
versionCode=101
