#Auto-incremented release version
#Wed Aug 19 13:17:37 IST 2026
releaseNotes=++fixed follow drop++
baseApkUrl=https\://feedpilot-api-ount.onrender.com/apk
forceUpdate=false
versionName=2.0.100
versionCode=102
